import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Header from "@/components/nav/Header";
import Footer from "@/components/nav/Footer";
import BootstrapActivation from "@/components/utils/BootstrapActivation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
            />
        </head>


        {/*<body className={`${geistSans.variable} ${geistMono.variable}`}>*/}
        {/*  {children}*/}
        {/*</body>*/}
            <body className={inter.className}>

                <Header/>
                    <div className="container">
                        <main role="main" className="pb-3">
                            {children}
                        </main>
                    </div>
                <Footer/>
                <BootstrapActivation/>
            </body>
        </html>
    );
}
